-- ============================================================
-- 01_setup_database.sql
-- Creates database, schemas, and all table structures.
-- Run with a role that has CREATE DATABASE privileges.
-- ============================================================

USE ROLE IDENTIFIER($DEMO_ROLE);
USE WAREHOUSE IDENTIFIER($DEMO_WAREHOUSE);

-- Database and schemas
CREATE DATABASE IF NOT EXISTS BEERCOMPANYDEMO;
CREATE SCHEMA IF NOT EXISTS BEERCOMPANYDEMO.BASE;
CREATE SCHEMA IF NOT EXISTS BEERCOMPANYDEMO.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS BEERCOMPANYDEMO.ML;

-- =========================
-- BASE schema tables
-- =========================
USE SCHEMA BEERCOMPANYDEMO.BASE;

CREATE OR REPLACE TABLE DIM_PRODUCTS (
    DIM_PRODUCT_MASTER_KEY NUMBER(38,0),
    PRODUCT_ID VARCHAR(18),
    MATERIAL_TYPE VARCHAR(4),
    MATERIAL_GROUP VARCHAR(9),
    BASE_UNIT_OF_MEASURE VARCHAR(3),
    PRODUCT_DESCRIPTION VARCHAR(40)
);

CREATE OR REPLACE TABLE DIM_PLANTS (
    DIM_STORAGE_LOCATIONS_KEY NUMBER(38,0),
    PLANT VARCHAR(4),
    PLANT_NAME VARCHAR(30),
    COMPANY_CODE VARCHAR(4),
    COMPANY_NAME VARCHAR(256),
    STORAGE_LOCATION VARCHAR(4),
    STORAGE_DESCRIPTION VARCHAR(50)
);

CREATE OR REPLACE TABLE FCT_INVENTORY_BASELINE (
    PRODUCT_ID VARCHAR(18),
    PLANT VARCHAR(4),
    STORAGE_LOCATION VARCHAR(4),
    ON_HAND_STOCK NUMBER(13,3)
);

-- =========================
-- ANALYTICS schema tables
-- =========================
USE SCHEMA BEERCOMPANYDEMO.ANALYTICS;

CREATE OR REPLACE TABLE WEEKLY_DATES (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    WEEK_END_DATE DATE
);

CREATE OR REPLACE TABLE GEOPOLITICAL_EVENTS (
    EVENT_ID NUMBER(38,0),
    EVENT_NAME VARCHAR(200),
    EVENT_CATEGORY VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE,
    SEVERITY NUMBER(38,0),
    AFFECTED_REGIONS VARCHAR(500),
    AFFECTED_DCS VARCHAR(200),
    SUPPLY_CHAIN_IMPACT VARCHAR(500),
    LEAD_TIME_IMPACT_PCT FLOAT,
    COST_IMPACT_PCT FLOAT,
    AFFECTED_MATERIALS VARCHAR(200)
);

CREATE OR REPLACE TABLE DISTRIBUTION_NETWORK (
    LOCATION_ID VARCHAR(10),
    LOCATION_NAME VARCHAR(100),
    LOCATION_TYPE VARCHAR(20),
    CITY VARCHAR(50),
    STATE VARCHAR(2),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    CAPACITY_UNITS NUMBER(38,0),
    PARENT_PLANT VARCHAR(10)
);

CREATE OR REPLACE TABLE SUPPLY_CHAIN_ROUTES (
    ROUTE_ID VARCHAR(10),
    ROUTE_DESCRIPTION VARCHAR(100),
    ORIGIN_ID VARCHAR(10),
    DESTINATION_ID VARCHAR(10),
    MATERIAL_TYPE VARCHAR(20),
    TRANSPORT_MODE VARCHAR(20),
    BASELINE_LEAD_DAYS NUMBER(4,0),
    ORIGIN_LAT FLOAT,
    ORIGIN_LON FLOAT,
    DEST_LAT FLOAT,
    DEST_LON FLOAT
);

CREATE OR REPLACE TABLE RAW_MATERIAL_PRICES (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    MATERIAL VARCHAR(10),
    UNIT VARCHAR(20),
    SPOT_PRICE FLOAT,
    BASELINE_PRICE FLOAT,
    EVENT_IMPACT_PCT FLOAT
);

CREATE OR REPLACE TABLE PRODUCT_COST_STRUCTURE (
    PRODUCT_ID VARCHAR(18),
    PRODUCT_DESCRIPTION VARCHAR(40),
    BEER_STYLE VARCHAR(20),
    PACK_TYPE VARCHAR(5),
    BARLEY_USAGE_PER_UNIT NUMBER(10,2),
    HOPS_USAGE_PER_UNIT NUMBER(10,2),
    OTHER_COGS_PER_UNIT NUMBER(11,2),
    BASE_RETAIL_PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE WEEKLY_SALES (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    PRODUCT_ID VARCHAR(18),
    PRODUCT_DESCRIPTION VARCHAR(40),
    BEER_STYLE VARCHAR(20),
    PACK_TYPE VARCHAR(5),
    DC_ID VARCHAR(10),
    DC_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(5),
    UNITS_SOLD FLOAT,
    SELLING_PRICE NUMBER(22,2),
    UNIT_COGS FLOAT,
    BARLEY_USAGE_PER_UNIT NUMBER(10,2),
    HOPS_USAGE_PER_UNIT NUMBER(10,2),
    OTHER_COGS_PER_UNIT NUMBER(11,2)
);

CREATE OR REPLACE TABLE WEEKLY_SHIPMENTS (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    ROUTE_ID VARCHAR(10),
    ROUTE_DESCRIPTION VARCHAR(100),
    ORIGIN_ID VARCHAR(10),
    DESTINATION_ID VARCHAR(10),
    MATERIAL_TYPE VARCHAR(20),
    TRANSPORT_MODE VARCHAR(20),
    BASELINE_LEAD_DAYS NUMBER(4,0),
    ORIGIN_LAT FLOAT,
    ORIGIN_LON FLOAT,
    DEST_LAT FLOAT,
    DEST_LON FLOAT,
    ACTUAL_LEAD_DAYS FLOAT,
    DISRUPTION_FACTOR FLOAT,
    SHIPMENT_QTY_TONS FLOAT,
    FREIGHT_COST_PER_TON FLOAT,
    IS_DISRUPTED BOOLEAN,
    PRIMARY_DISRUPTION_EVENT VARCHAR(200),
    ROUTE_RISK_SCORE FLOAT
);

CREATE OR REPLACE TABLE WEEKLY_INVENTORY (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    DC_ID VARCHAR(10),
    DC_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(5),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ON_HAND_UNITS FLOAT,
    WEEKLY_DEMAND_UNITS FLOAT,
    INBOUND_SUPPLY_TONS FLOAT,
    AVG_SUPPLY_DISRUPTION FLOAT,
    AVG_LEAD_DAYS FLOAT,
    DAYS_OF_SUPPLY FLOAT,
    SAFETY_STOCK_THRESHOLD FLOAT,
    RISK_STATUS VARCHAR(10)
);

CREATE OR REPLACE TABLE WEEKLY_MARGIN_ANALYSIS (
    WEEK_NUM NUMBER(18,0),
    WEEK_START_DATE DATE,
    DC_ID VARCHAR(10),
    BEER_STYLE VARCHAR(20),
    PRODUCT_COUNT NUMBER(18,0),
    TOTAL_UNITS FLOAT,
    TOTAL_REVENUE FLOAT,
    TOTAL_COGS FLOAT,
    TOTAL_GROSS_PROFIT FLOAT,
    AVG_MARGIN_PCT FLOAT,
    BARLEY_PRICE FLOAT,
    HOPS_PRICE FLOAT,
    AVG_BARLEY_USAGE NUMBER(29,3),
    AVG_HOPS_USAGE NUMBER(29,3),
    TOTAL_BARLEY_COST FLOAT,
    TOTAL_HOPS_COST FLOAT,
    AVG_UNIT_MARGIN FLOAT,
    AVG_SELLING_PRICE NUMBER(38,2),
    AVG_UNIT_COGS FLOAT
);

CREATE OR REPLACE TABLE PRICING_SCENARIO_ANALYSIS (
    SCENARIO_NAME VARCHAR(30),
    SCENARIO_BARLEY_PRICE FLOAT,
    SCENARIO_HOPS_PRICE FLOAT,
    PRODUCT_ID VARCHAR(18),
    PRODUCT_DESCRIPTION VARCHAR(40),
    BEER_STYLE VARCHAR(20),
    RETAIL_PRICE NUMBER(12,2),
    BASELINE_COGS NUMBER(15,2),
    SCENARIO_COGS NUMBER(16,2),
    COGS_INCREASE_PCT FLOAT,
    BASELINE_MARGIN_PCT FLOAT,
    SCENARIO_MARGIN_PCT FLOAT,
    MARGIN_EROSION_PCT FLOAT,
    PRICING_ACTION VARCHAR(25),
    RECOMMENDED_PRICE NUMBER(21,2)
);
