-- ============================================================
-- 02_load_data.sql
-- Creates a file format and internal stage, then loads all
-- CSV files that were uploaded by setup.sh.
-- ============================================================

USE ROLE IDENTIFIER($DEMO_ROLE);
USE WAREHOUSE IDENTIFIER($DEMO_WAREHOUSE);

-- File format for our CSVs
CREATE OR REPLACE FILE FORMAT BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', '')
    EMPTY_FIELD_AS_NULL = TRUE;

-- Internal stage for data loading
CREATE OR REPLACE STAGE BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE
    FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT;

-- ============================================================
-- COPY INTO each table from the stage
-- (setup.sh uploads CSVs to @DATA_STAGE before this script runs)
-- ============================================================

-- BASE schema
COPY INTO BEERCOMPANYDEMO.BASE.DIM_PRODUCTS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/dim_products.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.BASE.DIM_PLANTS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/dim_plants.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.BASE.FCT_INVENTORY_BASELINE FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/fct_inventory_baseline.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';

-- ANALYTICS schema
COPY INTO BEERCOMPANYDEMO.ANALYTICS.WEEKLY_DATES FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/weekly_dates.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.GEOPOLITICAL_EVENTS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/geopolitical_events.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.DISTRIBUTION_NETWORK FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/distribution_network.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.SUPPLY_CHAIN_ROUTES FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/supply_chain_routes.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.RAW_MATERIAL_PRICES FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/raw_material_prices.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.PRODUCT_COST_STRUCTURE FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/product_cost_structure.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.WEEKLY_SALES FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/weekly_sales.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.WEEKLY_SHIPMENTS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/weekly_shipments.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.WEEKLY_INVENTORY FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/weekly_inventory.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.WEEKLY_MARGIN_ANALYSIS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/weekly_margin_analysis.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
COPY INTO BEERCOMPANYDEMO.ANALYTICS.PRICING_SCENARIO_ANALYSIS FROM @BEERCOMPANYDEMO.ANALYTICS.DATA_STAGE/pricing_scenario_analysis.csv FILE_FORMAT = BEERCOMPANYDEMO.ANALYTICS.CSV_FORMAT ON_ERROR = 'ABORT_STATEMENT';
