-- ============================================================
-- 03_create_views.sql
-- Creates views used as inputs to Snowflake ML models.
-- ============================================================

USE ROLE IDENTIFIER($DEMO_ROLE);
USE WAREHOUSE IDENTIFIER($DEMO_WAREHOUSE);
USE SCHEMA BEERCOMPANYDEMO.ANALYTICS;

-- Inventory forecast input (time series per DC)
CREATE OR REPLACE VIEW V_INVENTORY_FORECAST_INPUT AS
SELECT WEEK_START_DATE AS DS, DC_ID AS SERIES, ON_HAND_UNITS AS Y
FROM WEEKLY_INVENTORY
ORDER BY DC_ID, DS;

-- Raw material price forecast input
CREATE OR REPLACE VIEW V_PRICE_FORECAST_INPUT AS
SELECT WEEK_START_DATE AS DS, MATERIAL AS SERIES, SPOT_PRICE AS Y
FROM RAW_MATERIAL_PRICES
ORDER BY MATERIAL, DS;

-- Anomaly detection: all shipment destinations
CREATE OR REPLACE VIEW V_ANOMALY_INPUT AS
SELECT WEEK_START_DATE AS DS, DESTINATION_ID AS SERIES, AVG(ACTUAL_LEAD_DAYS) AS Y
FROM WEEKLY_SHIPMENTS
GROUP BY WEEK_START_DATE, DESTINATION_ID
ORDER BY DESTINATION_ID, DS;

-- Train/test split for anomaly detection (train = first ~90 weeks)
CREATE OR REPLACE VIEW V_ANOMALY_TRAIN AS
SELECT DS, SERIES, Y FROM V_ANOMALY_INPUT WHERE DS < '2026-07-13';

CREATE OR REPLACE VIEW V_ANOMALY_TEST AS
SELECT DS, SERIES, Y FROM V_ANOMALY_INPUT WHERE DS >= '2026-07-13';

-- Top Insights: margin drivers (label = recent 6 months as test)
CREATE OR REPLACE VIEW V_MARGIN_DRIVERS_INPUT AS
SELECT
    AVG_MARGIN_PCT AS METRIC,
    DC_ID,
    BEER_STYLE,
    BARLEY_PRICE,
    HOPS_PRICE,
    TOTAL_UNITS AS VOLUME,
    WEEK_START_DATE >= '2026-04-01' AS LABEL
FROM WEEKLY_MARGIN_ANALYSIS;
