-- ============================================================
-- 05_deploy_streamlit.sql
-- Uploads the Streamlit app and creates the SiS app object.
-- NOTE: The PUT command must be run via setup.sh (SnowSQL/CLI),
-- not from a worksheet.
-- ============================================================

USE ROLE IDENTIFIER($DEMO_ROLE);
USE WAREHOUSE IDENTIFIER($DEMO_WAREHOUSE);

-- Stage for Streamlit app files
CREATE OR REPLACE STAGE BEERCOMPANYDEMO.ANALYTICS.STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Upload is handled by setup.sh via:
--   PUT file://streamlit_app.py @BEERCOMPANYDEMO.ANALYTICS.STREAMLIT_STAGE
--        AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Create the Streamlit app
CREATE OR REPLACE STREAMLIT BEERCOMPANYDEMO.ANALYTICS.BEER_SUPPLY_CHAIN_DASHBOARD
    ROOT_LOCATION = '@BEERCOMPANYDEMO.ANALYTICS.STREAMLIT_STAGE'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = IDENTIFIER($DEMO_WAREHOUSE)
    TITLE = 'Beer Co. Supply Chain & Pricing Intelligence';

-- Grant access to ACCOUNTADMIN (optional, for demo sharing)
GRANT USAGE ON DATABASE BEERCOMPANYDEMO TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA BEERCOMPANYDEMO.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA BEERCOMPANYDEMO.ML TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA BEERCOMPANYDEMO.BASE TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA BEERCOMPANYDEMO.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA BEERCOMPANYDEMO.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA BEERCOMPANYDEMO.ML TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA BEERCOMPANYDEMO.BASE TO ROLE ACCOUNTADMIN;
GRANT USAGE ON STREAMLIT BEERCOMPANYDEMO.ANALYTICS.BEER_SUPPLY_CHAIN_DASHBOARD TO ROLE ACCOUNTADMIN;
GRANT READ ON STAGE BEERCOMPANYDEMO.ANALYTICS.STREAMLIT_STAGE TO ROLE ACCOUNTADMIN;
